export {
  record_outcome,
  suggest_improvements,
  find_similar_solutions,
  create_pattern,
  get_success_patterns,
  create_insight,
  get_insights,
  apply_insight,
  auto_generate_insights,
  get_learning_stats,
  type RecordOutcomeInput,
  type SuggestImprovementsInput,
  type FindSimilarSolutionsInput,
  type CreatePatternInput,
  type GetSuccessPatternsInput,
  type CreateInsightInput,
  type GetInsightsInput,
  type ApplyInsightInput,
} from './learning_tools.js';

export {
  memory_link,
  pattern_link,
  memory_to_pattern_link,
  get_connected_nodes,
  get_knowledge_subgraph,
  suggest_links,
  get_related_memories,
  auto_build_links,
  get_knowledge_stats,
  link_solution_to_error,
  type MemoryLinkInput,
  type LinkPatternInput,
  type LinkMemoryToPatternInput,
  type GetConnectedNodesInput,
  type GetKnowledgeSubgraphInput,
  type SuggestLinksInput,
  type GetRelatedMemoriesInput,
  type LinkSolutionToErrorInput,
} from './knowledge_tools.js';
